### ISSUE TITLE
`required` keys declared on the parent schema's own `properties` fall into the `Extract<keyof T, ...>` guard and lose requiredness with `additionalProperties` (regression in 8.22.0)

### ISSUE THREAD

**Issue by wadakatu** [orval-labs/orval#3750]
### Description

Since v8.22.0 (#3721), `required` keys whose properties are declared on the composing schema's **own top-level `properties`**, while the `required` marker lives in a constraint-only `allOf` member (an overlay with `required` but no `properties`), are treated as unresolvable and wrapped in the `Extract<keyof T, ...>` guard:

```ts
Required<Pick<T, Extract<keyof T, 'id' | 'name'>>>
```

As in #3748, with `additionalProperties: true` the emitted intersection carries an index signature, `keyof T` collapses to `string | number`, `Extract<...>` evaluates to `never`, and the required override becomes a no-op — **properties the OpenAPI document declares as `required` silently become optional**. The generated code still compiles, so nothing fails in CI.

This is the sibling of #3748 (fixed by #3749): that fix resolves keys reached through `allOf` **members** (including nested `$ref` compositions), but the parent schema's own `properties` are still never fed into the resolvability check, so this shape remains misclassified on master with #3749 applied.

### Output client

fetch (the model emission is shared, so any client is affected)

### Configuration (orval.config)

```ts
import { defineConfig } from 'orval';

export default defineConfig({
  repro: {
    input: {
      target: './api.yaml',
    },
    output: {
      target: './generated/repro.ts',
      client: 'fetch',
    },
  },
});
```

### Environment

```
  System:
    OS: macOS 26.5.1
    CPU: (11) arm64 Apple M3 Pro
    Shell: 5.9 - /bin/zsh
  npmPackages:
    orval: 8.22.0 (also reproduced on current master with #3749 applied; typescript 6.0.3)
```

### Expected behavior

Same output as v8.20.0 — a plain `Required<Pick>`:

```ts
export type ItemDetail = { [key: string]: unknown } & {
  id?: string;
  name?: string;
  [key: string]: unknown;
} & Required<Pick<{ [key: string]: unknown } & {
  id?: string;
  name?: string;
  [key: string]: unknown;
}, 'id' | 'name'>>;
```

This is valid TS (`'id' | 'name'` satisfies `keyof T` because `keyof T` widens to `string | number`) and enforces requiredness:

```ts
declare const item: ItemDetail;
const id: string = item.id; // OK on 8.20.0
```

### Actual behavior

The keys are wrapped in `Extract<keyof (...), 'id' | 'name'>`, which evaluates to `never`:

```ts
export type ItemDetail = { [key: string]: unknown } & {
  id?: string;
  name?: string;
  [key: string]: unknown;
} & Required<Pick<{ [key: string]: unknown } & {
  id?: string;
  name?: string;
  [key: string]: unknown;
}, Extract<keyof ({ [key: string]: unknown } & {
  id?: string;
  name?: string;
  [key: string]: unknown;
}), 'id' | 'name'>>>;
```

```ts
declare const item: ItemDetail;
const id: string = item.id;
// error TS2322: Type 'string | undefined' is not assignable to type 'string'.
```

### OpenAPI document (minimal, if applicable)

```yaml
openapi: 3.0.3
info:
  title: Repro
  version: 0.0.0
paths:
  /item:
    get:
      operationId: getItem
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemDetail'
components:
  schemas:
    ItemDetail:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      additionalProperties: true
      allOf:
        - type: object
          required:
            - id
            - name
          additionalProperties: true
```

The key ingredients are:

1. The `required` keys live on the **parent schema's own `properties`**, not in any `allOf` member. The constraint-only overlay member (`required` without `properties`) is the #3663 sparse-fieldset pattern, so the keys correctly reach the required-override machinery — but the resolvability check never sees them.
2. `additionalProperties: true`, which produces the index signature that makes the `Extract` guard collapse to `never`. Without it the emitted guard happens to preserve the keys and is merely cosmetic.

### Additional context

- Root cause: the pickable/unresolved split introduced by #3721 in `combineValues` (`packages/core/src/getters/combine.ts`) is driven by `resolvedData.allProperties`, which is collected exclusively from the resolved `allOf` **members** (since #3749 including their nested compositions). The parent/normalized schema's own `properties` keys are never pushed into it, so they always classify as unresolved.
- The fix looks small: the emitted intersection (`joined`) always includes the parent's own object emission, so its property keys are provably present in the picked type and adding `Object.keys(normalizedSchema.properties ?? {})` to the pickable set is safe — no `Extract` guard needed for them.
- Noted as a known limitation in #3749's description; splitting it out per scope.

**Comment by melloware** [comment]
@wadakatu assigned to you!
