### ISSUE TITLE
Incorrect syntax in the output file after upgrading to v7.6.0

### ISSUE THREAD

**Issue by amielucha** [orval-labs/orval#1948]
Updating to version `7.6.0` results in an erroneous output.

The input extracted from the schema:

```
      "ProcessDataStandardV1Other": {
        "type": "object",
        "properties": {

        },
        "additionalProperties": true,
        "description": ""
      },
```

The correct output from version `7.5.0`:

```ts
export interface ProcessDataStandardV1Other { [key: string]: unknown }
```

The incorrect output from version `7.6.0`:

```ts
export const ProcessDataStandardV1OtherValue = { [key: string]: unknown } as const;
export type ProcessDataStandardV1Other = typeof ProcessDataStandardV1OtherValue;

```

This results in a TypeScript Error:

```sh
Cannot find name 'key'. Did you mean 'Key'?ts(2552)

'string' only refers to a type, but is being used as a value here.
```

**Comment by melloware** [comment]
cc @fjodor-rybakov  this broke with this ticket: https://github.com/orval-labs/orval/issues/1849

**Comment by fjodor-rybakov** [comment]
> cc [@fjodor-rybakov](https://github.com/fjodor-rybakov) this broke with this ticket: [#1849](https://github.com/orval-labs/orval/issues/1849)

Fix: https://github.com/orval-labs/orval/pull/1949

**Comment by melloware** [comment]
Thanks @fjodor-rybakov

**Comment by karlismelderis-mckinsey** [comment]
Can you please release this fix?
we cannot update Orval dependency until fix is released
