### ISSUE TITLE
v8: unused `axiosInstance` param generated

### ISSUE THREAD

**Issue by yekver** [orval-labs/orval#2877]
### Description

After upgrading to v8, generated API modules include an `axiosInstance` parameter in the exported API factory functions. This triggers a TypeScript compilation error with `noUnusedParamenters: true`.
This did not happen with v7.

### Configuration (orval.config)

```ts
tsconfig: './tsconfig.json'
client: 'axios',
httpClient: 'axios'
mode: 'tags-split'
override: {
  mutator: {
    path: 'src/axiosInstance.ts'
  }
}
```

### Environment

Orval: v8.1
OpenAPI: 3.0.3
NodeJS: 22.22

### Expected behavior

```ts
export const getPetsApi = () => { .... }
```

If `override.mutator` is used, do not generate `axiosInstance` parameter at all.

### Actual behavior

```ts
export const getPetsApi = (axiosInstance: AxiosInstance = axios) => { .... }
```

**Comment by melloware** [comment]
@FR073N  looks like a bug introduced?

**Comment by jaem0629** [comment]
I've fixed the bug and submitted PR #2884

**Comment by FR073N** [comment]
Sorry didn't thought about that. Actually your fix is good @jaem0629 , having mutator should not inject the instance. Thanks.
