### ISSUE TITLE
mock: MSW file missing import for __-aliased types when using nullable $ref (anyOf: [$ref, {type: null}])

### ISSUE THREAD

**Issue by yamaaaaaa31** [orval-labs/orval#3269]
## Description

Starting in v8.8.1, schemas referenced via the OpenAPI 3.1 nullable-ref pattern (`anyOf: [{$ref: ...}, {type: null}]`) are imported into the main endpoint file with a `__`-prefixed alias (e.g. `Widget as __Widget`), and the type reference in the endpoint file uses the aliased name. However, the companion `.msw.ts` file **also uses the aliased name (`__Widget`) but never imports it**, producing `TS2304: Cannot find name '__Widget'` on compile.

This is a regression from v8.8.0, where both files imported the bare name `Widget`. The change appears to have been introduced by #3245 (`fix(core): support oneOf/anyOf in multipart/form-data code generation`), whose snapshot diff for `tests/__snapshots__/react-query/importFromSubdirectory/endpoints.msw.ts` adds `AnotherSchema as __AnotherSchema` imports. That PR's snapshot happens to include both bare and aliased imports on the msw side, but in the split-mode + nullable-anyOf-ref scenario below, the msw generator emits zero import for the aliased name.

The nullable-ref `anyOf` pattern is the default shape FastAPI/Pydantic emits for `Optional[Model]` response/request bodies, so this breaks a very common real-world case. Downgrading to `orval@8.8.0` against the exact same OpenAPI spec and orval config produces correct output.

## Output client

`react-query` (affects the MSW mock generator; likely any client combined with `mock: { type: 'msw' }`)

## Configuration (orval.config)

```js
// orval.config.mjs
export default {
  repro: {
    input: { target: './openapi.json' },
    output: {
      mode: 'tags-split',
      target: './generated',
      schemas: './generated/model',
      client: 'react-query',
      mock: { type: 'msw' },
      clean: true,
    },
  },
};
```

## Environment

```
System:
  OS: macOS 26.3.1 (darwin arm64) — also reproduces on Linux
  Node: v22+
npmPackages:
  orval: 8.8.1
  msw: 2.13.4
  typescript: 5.9.3
```

## Expected behavior

Generated with `orval@8.8.0` (working):

```ts
// generated/default/default.ts
import type { Widget } from '../model';
export type getWidgetResponse200 = { data: Widget | null; status: 200 };
```

```ts
// generated/default/default.msw.ts
import type { Widget } from '../model';
export const getGetWidgetResponseMock = (): Widget | null => (...)
```

## Actual behavior

Generated with `orval@8.8.1`:

```ts
// generated/default/default.ts — type imported with __ alias
import type { Widget as __Widget } from '../model';
export type getWidgetResponse200 = { data: __Widget | null; status: 200 };
```

```ts
// generated/default/default.msw.ts — uses __Widget but NEVER imports it
import { faker } from '@faker-js/faker';
import { HttpResponse, http } from 'msw';
import type { RequestHandlerOptions } from 'msw';
// ^ no import of Widget or __Widget at all

export const getGetWidgetResponseMock = (): __Widget | null => (...)
//                                            ^^^^^^^^ TS2304
```

`tsc --noEmit` output:

```
generated/default/default.msw.ts(20,45): error TS2304: Cannot find name '__Widget'.
generated/default/default.msw.ts(23,60): error TS2304: Cannot find name '__Widget'.
generated/default/default.msw.ts(23,144): error TS2304: Cannot find name '__Widget'.
generated/default/default.msw.ts(23,163): error TS2304: Cannot find name '__Widget'.
```

## OpenAPI document (minimal)

```json
{
  "openapi": "3.1.0",
  "info": { "title": "Repro", "version": "0.0.1" },
  "paths": {
    "/widgets": {
      "get": {
        "operationId": "get_widget",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "anyOf": [
                    { "$ref": "#/components/schemas/Widget" },
                    { "type": "null" }
                  ],
                  "title": "Response Get Widget"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Widget": {
        "type": "object",
        "properties": {
          "id": { "type": "string" },
          "label": { "type": "string" }
        },
        "required": ["id", "label"],
        "title": "Widget"
      }
    }
  }
}
```

## Additional context

- Confirmed bisect: `orval@8.8.0` emits correct code from the identical config+spec; `orval@8.8.1` reproduces the TS2304.
- Suspected source: #3245. The snapshot diff adds `__`-aliased imports on the msw side, but the emission path for the split-mode + nullable-anyOf-ref case does not include the alias import.
- Also affects request bodies with `anyOf: [{$ref: Foo}, {type: null}]` schemas — in that case the body param is additionally renamed to `_fooNull` while the type alias `__Foo` is referenced without import in the msw mock.
- Affects any client when `mock: { type: 'msw' }` is enabled; reproduced against `react-query`, likely identical on `fetch` / `axios` / `swr`.
- Real-world occurrence: FastAPI/Pydantic emits exactly this shape for `Optional[Model]` response/request typing, so every endpoint with a nullable model body breaks compilation after upgrading to 8.8.1.

**Comment by melloware** [comment]
Cc @nathansogut-sipios looks like your fix was not complete

**Comment by nathansogut-sipios** [comment]
Hi @melloware @yamaaaaaa31, sorry for the late reply, fresh GitHub account for the previous PR, lost the habit of checking notifications. Won't happen again.

Looking into it now. Doesn't look like it's been picked up yet, so I'll take a stab at a fix with a regression test. 

If I can't land something clean in reasonable time, I'll fall back to reverting https://github.com/orval-labs/orval/pull/3245 and re-attack the original issue with a more narrowly scoped fix.

Will report back shortly.

(I'm open to any suggestions)

**Comment by nathansogut-sipios** [comment]
Hi @melloware @yamaaaaaa31, sorry for the late reply — I created a fresh GitHub account for the previous PR and completely lost the habit of checking notifications, so I didn't see the ping until today. Won't happen again.

Looking into this now. From a quick scan I don't think it's been picked up by anyone else yet, so I'll take a stab at a fix. I'll dig into the root cause first, then try to push a PR with a regression test that covers the nullable anyOf-ref + MSW split-mode case.

If I can't land a clean fix in a reasonable time, I'll fall back to reverting #3245 so the bug doesn't ship in the next release, and I'll re-open my original issue with a narrower repro that doesn't break this path. Open to suggestions if you'd prefer a different approach in the meantime.

Will report back shortly.

**Comment by nathansogut-sipios** [comment]
Hey @yamaaaaaa31 @melloware, opened #3279 with a fix. Two distinct root causes were involved (the over-broad scoping I introduced in #3245 + a pre-existing alias-blind import filter in the MSW mock), both are addressed. Verified against the spec in this issue and an additional request-body variant. Happy to iterate on review feedback.
