### ISSUE TITLE
bug(angular): httpResource output does not compile under exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by andsouto** [orval-labs/orval#3909]
### Description

Every generated `*.resource.ts` fails to compile when the consuming project has `"exactOptionalPropertyTypes": true`, with one error per file:

```
src/app/core/api/system/system.resource.ts(95,5): error TS2375: Type '{ headers: HttpHeaders | Record<string, string | readonly string[]> | undefined; url: string; ... }'
is not assignable to type 'HttpResourceRequest' with 'exactOptionalPropertyTypes: true'.
  Types of property 'headers' are incompatible.
    Type 'undefined' is not assignable to type 'HttpHeaders | Record<string, string | readonly string[]>'.
```

The offending line is in `applyOrvalRequestExtension`, emitted by the httpResource header template (introduced in #3717):

```ts
let next: HttpResourceRequest = { ...base };
const extraHeaders =
  typeof options.headers === 'function' ? options.headers() : options.headers;
if (extraHeaders !== undefined) {
  next = { ...next, headers: mergeOrvalResourceHeaders(next.headers, extraHeaders) }; // TS2375
}
```

`mergeOrvalResourceHeaders` is declared as returning `HttpResourceRequest['headers']`, which includes `undefined` because the property is optional. Under `exactOptionalPropertyTypes` an optional property may be *absent*, but not *present and `undefined`*, so the spread is rejected.

It is a typing issue only: the call is already inside `if (extraHeaders !== undefined)`, and `mergeOrvalResourceHeaders` returns `extra` when `base` is falsy, so the value is never actually `undefined` there. The neighbouring `context` branch is written in the compatible shape already.

`retrievalClient: 'httpResource'` and `'both'` are affected; `'httpClient'` is clean.

### Output client

angular

### Configuration (orval.config)

```ts
import { defineConfig } from 'orval';

export default defineConfig({
  api: {
    input: '../api/openapi.json',
    output: {
      clean: true,
      client: 'angular',
      mode: 'tags-split',
      override: {
        angular: { retrievalClient: 'both' },
      },
      schemas: 'src/app/core/api/model',
      target: 'src/app/core/api',
    },
  },
});
```

### Environment

```
System:
  OS: Linux 7.0 Ubuntu 26.04.1 LTS
  Node: 24.19.0
  pnpm: 11.22.0
npmPackages:
  @angular/common: 22.1.3 => 22.1.3
  @angular/core: 22.1.3 => 22.1.3
  orval: 8.25.0 => 8.25.0
  typescript: 6.0.3 => 6.0.3
```

Also reproduced on 8.26.0: the emitted template is identical (`@orval/angular@8.26.0`, `dist/index.mjs:1527`).

The only relevant tsconfig setting is:

```jsonc
{"compilerOptions": {"strict": true, "exactOptionalPropertyTypes": true}}
```

### Expected behavior

The generated client compiles in a project that enables `exactOptionalPropertyTypes`.

### Actual behavior

One `TS2375` per generated `*.resource.ts`, at the `headers` assignment in `applyOrvalRequestExtension`.

### OpenAPI document (minimal, if applicable)

```json
{
  "openapi": "3.1.0",
  "info": { "title": "demo", "version": "0.0.0" },
  "paths": {
    "/health": {
      "get": {
        "tags": ["system"],
        "responses": {
          "200": {
            "description": "ok",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "required": ["status"],
                  "properties": { "status": { "type": "string" } }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### Additional context

The operation shape does not matter: I reproduced it with the parameterless `GET` above, and with path params, optional and array query params, JSON request bodies and multipart uploads. In every case it is this one error per `.resource.ts` file and nothing else, so a fix here should unblock the whole `httpResource` output.

Suggested fix — set the key only when the merge produced a value, no behaviour change:

```ts
if (extraHeaders !== undefined) {
  const mergedHeaders = mergeOrvalResourceHeaders(next.headers, extraHeaders);
  next = mergedHeaders === undefined ? next : { ...next, headers: mergedHeaders };
}
```

Alternatively, overload `mergeOrvalResourceHeaders` so that a defined `extra` yields `NonNullable<HttpResourceRequest['headers']>`.

Happy to send the PR if you would like.

**Comment by melloware** [comment]
@the-ult looks like one for you?

**Comment by melloware** [comment]
@andsouto PR is welcome!
