### ISSUE TITLE
Mock: allOf creating invalid output

### ISSUE THREAD

**Issue by Kikketer** [orval-labs/orval#1807]
## What are the steps to reproduce this issue?

1. Have a schema that has `allOf` and an `allOf` array within it: https://github.com/Kikketer/orval-fail/blob/main/failure.openapi.yaml#L34
2. Generate
3. Notice that the generated ts files are invalid with `...data:` portions

## What happens?

` error TS1005: ',' expected`

The output will be invalid TS:  https://github.com/Kikketer/orval-fail/blob/main/__generated__/api.mock.ts#L64

## What were you expecting to happen?

Valid typescript files to be generated.

## Any logs, error output, etc?

```
error TS1005: ',' expected
```
But the problem is deeper in that
```
GetFailureResponse => ({...data: faker.helpers.arrayElement([{id: 
```
is invalid typescript

## Any other comments?

This works fine in 7.3.0.
The example file in the repo is a snippet and cleansed version of the real schema that we are using, so altering the schema to work isn't really an option.

## What versions are you using?

  System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 456.81 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    orval: 7.4.1 => 7.4.1

**Comment by SHergibo** [comment]
Related issue https://github.com/orval-labs/orval/issues/1692?

**Comment by melloware** [comment]
@SHergibo i think it is related.
