### ISSUE TITLE
🐞 Bug report: fetch client's getHeaders references undefined HeadersInit and returns Record<string,string> (8.25.0 regression, non-DOM lib)

### ISSUE THREAD

**Issue by yagop** [orval-labs/orval#3886]
### Description

Since **8.25.0**, the `fetch` client emits a `getHeaders` helper (added by the #3880 header-merge fix) that fails to type-check under a Node/Bun `tsconfig` whose `lib` does not include DOM. **8.24.0 is unaffected** (it emits no `getHeaders`).

Generated (8.25.0):

```ts
const getHeaders = (h?: HeadersInit | Headers): Record<string, string> => {
  if (!h) return {};
  if (h instanceof Headers) return Object.fromEntries(h.entries());
  if (Array.isArray(h)) return Object.fromEntries(h);
  // ...
```

Two problems appear with an explicit non-DOM `lib` (e.g. `["ES2022"]` / `["ESNext"]`), `@types/node`@26 + `@types/bun` in scope:

1. **`HeadersInit` is not defined.** `@types/node`@26's undici web-globals declare `Headers`/`RequestInit` but not the `HeadersInit` alias, and it isn't part of the JS libs:
   ```
   error TS2304: Cannot find name 'HeadersInit'.
   ```
   (Bumping `@types/node` doesn't help — the alias is intentionally absent.)

2. Even once `HeadersInit` is supplied, `getHeaders`' `Record<string, string>` return is **incompatible with fetch header values typed `string | readonly string[]`**:
   ```
   error TS2345 / TS2322: 'Record<string, string | readonly string[]>' is not assignable to 'Record<string, string>'
   ```

The regression is **masked** when `lib` includes DOM (or when `lib` is omitted, since TS's default lib set includes `DOM`/`DOM.Iterable`), which is why it doesn't affect most frontend consumers. It only surfaces with an explicit non-DOM `lib`, as is common for Node/Bun server projects.

Confirmed on 8.25.0:

| `lib` | Result |
| --- | --- |
| `["ESNext"]` | ❌ 104 × `TS2304` |
| `["ES2022", "DOM", "DOM.Iterable"]` | ✅ clean |
| `["ESNext", "DOM", "DOM.Iterable"]` | ✅ clean |

8.24.0 type-checks cleanly with `["ES2022"]`.

### Output client

fetch

### Configuration (orval.config)

```ts
import { defineConfig } from 'orval';

const SPECS: Record<string, string> = {
  trading: 'https://docs.alpaca.markets/openapi/trading-api.json',
  // ...
};

// fetch client with a custom mutator
const coreClient = (api: string) => ({
  input: { target: SPECS[api] },
  output: {
    client: 'fetch',
    target: `packages/core/src/generated/${api}/client.ts`,
    schemas: `packages/core/src/generated/${api}/model`,
    baseUrl: '',
    override: { mutator: { path: 'packages/core/src/mutator.ts', name: `${api}Mutator` } },
  },
});

export default defineConfig({
  'core-trading': coreClient('trading'),
  // ...
});
```

### Environment

```
System:  Ubuntu 26.04 LTS, arm64, container
Binaries: Node 26.7.0, npm 11.19.0, bun 1.3.14
npmPackages:
  orval: 8.25.0
  typescript: 5.9.3
  @types/node: 26.0.0
  @types/bun: 1.3.14
```

### Expected behavior

The generated fetch client type-checks without requiring the DOM lib, and header handling is compatible with the standard `string | readonly string[]` header value type.

### Actual behavior

`tsc --noEmit` fails: `TS2304: Cannot find name 'HeadersInit'`, and (once `HeadersInit` is provided) `TS2345`/`TS2322` inside `getHeaders` due to the `Record<string, string>` return type.

### Additional context

Two suggestions:

- Reference the header type without requiring DOM — e.g. derive it from `NonNullable<RequestInit['headers']>` rather than the DOM-only `HeadersInit` global.
- Make `getHeaders` normalize/return a type compatible with multi-valued (`readonly string[]`) header values, so it type-checks against both node/undici and Bun fetch types.

Regressed between 8.24.0 (fine) and 8.25.0 — likely introduced by the #3880 header-merge fix.

**Comment by melloware** [comment]
@ErfanBagheri404 looks like your fix caused a regression

**Comment by melloware** [comment]
8.26.0 is release with this fix if you want to give it another try

**Comment by yagop** [comment]
Thanks @ErfanBagheri404  & @melloware 

8.26.0  working fine 👍
