### ISSUE TITLE
Zod: 8.5.0 fails generating zod for string with format email + regex

### ISSUE THREAD

**Issue by jandry** [orval-labs/orval#3073]
### Description

When upgrading orval from 8.3.0 to 8.4.x or 8.5.x, it fail generation of zod client when openapi have email type and regex
My openapi has something like that
`
        owner:
          description: Owner of the team
          type: string
          format: email
          pattern: ^[a-zA-Z0-9._%+-]+@mycompany\.com$
`

8.5.0 generation do something like that
`
            owner: zod
                .email()
                .stringFormat('email', getTeamsResponseItemsItemOwnerRegExp)
                .optional()
                .describe('Owner of the team'),
`
but compilation says Property 'stringFormat' does not exist on type 'ZodEmail'.

Generation 8.3.0 was like this:

`
            owner: zod.email().regex(getTeamsResponseItemsItemOwnerRegExp).optional().describe('Owner of the team'),
`

### Configuration (orval.config)

```ts
export default {
    client: {
        input: './openapi.yml',
        output: {
            target: './client/src/zod.ts',
            client: 'zod',
            mode: 'single',
        },
    },
};
```

### Environment

  System:
    OS: macOS 26.3.1
    CPU: (8) arm64 Apple M3
    Memory: 90.95 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    zod: 4.3.6 => 4.3.6 

### Expected behavior

Generate working code compatible with zod

### Actual behavior

Generate non working code

### OpenAPI document (minimal, if applicable)

```yaml
openapi: 3.0.3
info:
  title: Demo
  version: 0.0.0
paths: {}

components:
  schemas:
    Empty:
      type: object
      properties: {}
      additionalProperties: false
    Team:
      type: object
      properties:
        teamId:
          type: string
          description: Team id
        displayName:
          description: Display name of the team
          type: string
        description:
          description: Description of the team
          type: string
          maxLength: 200
        owner:
          description: Owner of the team
          type: string
          format: email
          pattern: ^[a-zA-Z0-9._%+-]+@mycompany\.com$
        contactEmail:
          description: Contact email of the team
          type: string
          format: email
```

**Comment by melloware** [comment]
@the-ult any interest in looking at this one?

**Comment by melloware** [comment]
i "think" this PR fixes it https://github.com/orval-labs/orval/pull/3093
