### ISSUE TITLE
includeZodSchemaInArguments: react-query + fetch httpClient + custom mutator keeps the schema import type-only

### ISSUE THREAD

**Issue by Inv1x** [orval-labs/orval#4058]
### Description

With `client: 'react-query'`, `httpClient: 'fetch'`, a custom `mutator`, `schemas: { type: 'zod' }`, `override.fetch.runtimeValidation: true` and `override.includeZodSchemaInArguments: true` (the combination introduced in #3226 for #2858), the generated request function passes `schema: <ZodSchema>` to the mutator as intended, but the schema is still imported with `import type { ... } from '../model'`. TypeScript rejects the generated file:

```
error TS1361: 'SignInResponse' cannot be used as a value because it was imported using 'import type'.
```

The pure `fetch` client handles this: `packages/fetch/src/index.ts` (`generateClient`) calls `rewriteImportsForResponseValidation(..., { includeOutputType: !verbOptions.mutator })`, so the schema value import stays even with a mutator (see the comment next to it: "the schema value import stays, for `includeZodSchemaInArguments`").

The query client does not: `packages/query/src/index.ts` gates the same rewrite on `verbOptions.override.query.runtimeValidation?.enabled && ... && !verbOptions.mutator` (v8.30.0, around line 107-110). With a mutator the rewrite is skipped entirely, while the fetch request function generator still emits `schema: X` based on `override.fetch.runtimeValidation` + `includeZodSchemaInArguments`. Result: value usage, type-only import.

### Output client

react-query (httpClient: fetch), with `override.mutator`

### Configuration (orval.config)

```ts
import { defineConfig } from 'orval'

export default defineConfig({
  petstore: {
    input: { target: './petstore.yaml' },
    output: {
      mode: 'tags-split',
      target: './src/generated',
      schemas: { path: './src/generated/model', type: 'zod' },
      client: 'react-query',
      httpClient: 'fetch',
      override: {
        mutator: { path: './src/custom-fetch.ts', name: 'customFetch' },
        includeZodSchemaInArguments: true,
        fetch: { runtimeValidation: true },
      },
    },
  },
})
```

```ts
// src/custom-fetch.ts
import type { ZodType } from 'zod'

export const customFetch = async <T>(
  url: string,
  options?: RequestInit & { schema?: ZodType<T> },
): Promise<T> => {
  const { schema, ...init } = options ?? {}
  const response = await fetch(url, init)
  const data = await response.json()
  return schema ? schema.parse(data) : (data as T)
}
```

### Environment

- orval 8.30.0
- zod 4.5.4
- TypeScript 7.0.2 (same with 5.9.3)
- Bun 1.4.2 / macOS

### Expected behavior

Generated code imports the schema as a value when it is passed to the mutator, matching the `fetch` client output:

```ts
import type { ListPetsParams } from '../model'
import { Pets } from '../model'

export const listPets = async (params?: ListPetsParams, options?: Parameters<typeof customFetch>[1]): Promise<Pets> => {
  return customFetch<Pets>(getListPetsUrl(params), {
    ...options,
    method: 'GET',
    schema: Pets,
  })
}
```

### Actual behavior

```ts
import type { ListPetsParams, Pets } from '../model'

export const listPets = async (params?: ListPetsParams, options?: Parameters<typeof customFetch>[1]): Promise<Pets> => {
  return customFetch<Pets>(getListPetsUrl(params), {
    ...options,
    method: 'GET',
    schema: Pets, // TS1361
  })
}
```

### OpenAPI document (minimal, if applicable)

Reproduces with the repo's petstore sample; any operation with a JSON object response.

### Additional context

Current workaround: an `afterAllFilesWrite` hook that finds `schema: X` usages and moves those names from the `import type { ... } from '../model'` statement into a value import. It would be better if the query generator applied the value-import rewrite whenever `includeZodSchemaInArguments` is active, independently of the `!mutator` guard that only makes sense for the generated `Schema.parse()` call.

Related: #2858, #3226.
