### PR TITLE
fix(msw): simplify combine

### LINKED ISSUE #1526: MSW: Error using oneOf nested inside allOf
Minimal input schema:

```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "bug report"
  },
  "paths": {
    "/something": {
      "post": {
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "uploads": {
                      "type": "array",
                      "items": {
                        "allOf": [
                          {
                            "type": "object",
                            "properties": {
                              "file_type": {
                                "type": "string"
                              }
                            }
                          },
                          {
                            "oneOf": [
                              {
                                "type": "object",
                                "properties": {
                                  "type": {
                                    "type": "string",
                                    "enum": ["a"]
                                  }
                                }
                              },
                              {
                                "type": "object",
                                "properties": {
                                  "type": {
                                    "type": "string",
                                    "enum": ["b"]
                                  },
                                  "other": {
                                    "type": "string"
                                  }
                                }
                              }
                            ]
                          }
                        ]
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

```

Output with syntax error:
```ts
export const getPostSomethingResponseMock = (overrideResponse: Partial< PostSomething200 > = {}): PostSomething200 => ({uploads: faker.helpers.arrayElement([Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({file_type: faker.helpers.arrayElement([faker.word.sample(), undefined]),{type: faker.helpers.arrayElement([faker.helpers.arrayElement(['a'] as const), undefined])},{other: faker.helpers.arrayElement([faker.word.sample(), undefined]), type: faker.helpers.arrayElement([faker.helpers.arrayElement(['b'] as const), undefined])}})), undefined]), ...overrideResponse})
```

Tested on orval 6.29.1 and 6.31.0. The code in the schema file and the API file is correct; only the MSW file has this problem.

This seems to only happen with a `oneOf` nested inside an `allOf`.

### LINKED ISSUE #1692: Mocks (for MSW) are wrongly generated with deeply nested objects
## What are the steps to reproduce this issue?
**YAML Path**
```
  '/api/tenants/{tenantId}':
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantComposite'
```
**YAML Schema**
```
    TenantComposite:
      allOf:
        - $ref: '#/components/schemas/Tenant'

    TenantComposite:
      allOf:
        - $ref: '#/components/schemas/Tenant'
        
    Tenant:
      allOf:
        - $ref: '#/components/schemas/TenantLight'
```

## What happens?
In the .msw file, it generates the following:
`export const getGetApiTenantsTenantIdResponseMock = (): TenantCompositeDto => ({...enabled: faker.datatype.boolean(), `

## What were you expecting to happen?
In the .msw file, it generated the following:
`export const getGetApiTenantsTenantIdResponseMock = (): TenantCompositeDto => ({enabled: faker.datatype.boolean(),`

## What versions are you using?
7.2.0

### LINKED ISSUE #1807: Mock: allOf creating invalid output
## What are the steps to reproduce this issue?

1. Have a schema that has `allOf` and an `allOf` array within it: https://github.com/Kikketer/orval-fail/blob/main/failure.openapi.yaml#L34
2. Generate
3. Notice that the generated ts files are invalid with `...data:` portions

## What happens?

` error TS1005: ',' expected`

The output will be invalid TS:  https://github.com/Kikketer/orval-fail/blob/main/__generated__/api.mock.ts#L64

## What were you expecting to happen?

Valid typescript files to be generated.

## Any logs, error output, etc?

```
error TS1005: ',' expected
```
But the problem is deeper in that
```
GetFailureResponse => ({...data: faker.helpers.arrayElement([{id: 
```
is invalid typescript

## Any other comments?

This works fine in 7.3.0.
The example file in the repo is a snippet and cleansed version of the real schema that we are using, so altering the schema to work isn't really an option.

## What versions are you using?

  System:
    OS: macOS 15.1.1
    CPU: (12) arm64 Apple M3 Pro
    Memory: 456.81 MB / 36.00 GB
    Shell: 5.9 - /bin/zsh
  npmPackages:
    orval: 7.4.1 => 7.4.1

### PR DESCRIPTION
**Pull request by AllieJonsson**
## Status

**READY**

## Description

Rewrite `combine.ts` a bit to solve some nested all-of, any-of and one-of issues. (hide whitespace in diff view to get a better view of what changed)
Fixes #1807 
Fixes #1526 
Fixes #1692 

## Todos

- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

### CODE REVIEW

**Comment by AllieJonsson** [comment]
I hope we had tests for all previously known cases. I also tried all specs in the linked issues, hope I didn't miss any edge case

**Review by melloware — DISMISSED** [review]

**Comment by melloware** [comment]
@AllieJonsson this is great!   I will let the others review but I know this has been a pain for MSW users.

**Comment by anymaniax** [comment]
To be honest I don’t remember all the cases neither 😅. Maybe it’s better to start with that and  some tests for each cases that we know for now and build on it after?

**Comment by soartec-lab** [comment]
I'll check the operation with several OpenAPIs I have on hand. Please give me a moment.

**Comment by soartec-lab** [comment]
I checked and there were some regressions. I will report the details again 👍

**Comment by soartec-lab** [comment]
@AllieJonsson 

The details of the error are below:

```yaml
paths:
  /pets:
    get:
      operationId: get-pets
      responses:
        '200':
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Pets'
                type: array
          description: OK
components:
  schemas:
    Pets:
      properties:
        petId:
          allOf:
            - $ref: '#/components/schemas/DogId'
            - $ref: '#/components/schemas/CatId'
          nullable: true 
    DogId:
      nullable: true
      type: string
    CatId:
      description: サービス申込者用コンテンツID
      type: string
```

It seems that an error occurs in the definition when referencing the schema with ref.
generated:

```
export const getGetPetsResponseMock = (): Pets[] => (Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({petId: faker.helpers.arrayElement([{faker.helpers.arrayElement([faker.string.alpha(20), null]),faker.string.alpha(20),}, undefined])})))
```

and occured error `error TS1005: ',' expected.`

**Comment by soartec-lab** [comment]
@AllieJonsson 

Thank you. I have confirmed that this case has been fixed 👍 
However, it seems that the case still remains. I found that `allOf` referenced from `ref` is an error.

```yaml
/pet:
    get:
      operationId: get-pet
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
          description: OK
      tags:
        - Pet
components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - detail
      properties:
        id:
          type: string
        detail:
          allOf:
            - $ref: '#/components/schemas/Name'
    Name:
      type: string
```


```
Property assignment expected.

18 export const getGetPetResponseMock = (overrideResponse: Partial< Pet > = {}): Pet => ({id: faker.string.alpha(20), detail: faker.string.alpha(20),, ...overrideResponse})
```

**Comment by soartec-lab** [comment]
@AllieJonsson 

This is perfect 🎉 
It also supports complex `OpenAPI` definitions that I have at hand, dealing with polymorphism and nesting in `ref`.

**Review by soartec-lab — APPROVED** [review]
